### ISSUE TITLE
Clean up branches

### ISSUE THREAD

**Issue by hbgit** [hbgit/Map2Check#17]
Checkout the following branches, aiming to update or remove from the project:

- [x] feature/code_style
- [x] feature/dockerfiles
- [x] feature/force_predassume
- [x] feature/llvmbc-input
- [x] feature/loops
- [x] crabllvm
- [ ] feature/memderef-fix
- [x] feature/new-build
- [ ] feature/sqlite
- [ ] feature/svcomp19
- [x] quickfix/allocation_test_fix
- [x] feature/regressiontest

**Comment by rafaelsamenezes** [comment]
Besides feature/force_predassume I think that all  other can be deleted. @hbgit do you know what this branch is intended to?

**Comment by hbgit** [comment]
feature/force_predassume was one branch to generate assumes based on all pre-condition from the analyzed program, but the experiments results was not good.

**Comment by hbgit** [comment]
After analysing the branches, I'll delete the following branches:

- [x] feature/code_style
- [x] feature/dockerfiles
- [x] feature/force_predassume
- [x] feature/llvmbc-input
- [x] feature/loops
- [x] crabllvm
- [x] feature/new-build
- [x] quickfix/allocation_test_fix
- [x] feature/regressiontesting
