### ISSUE TITLE
Support the reach_error() function

### ISSUE THREAD

**Issue by hbgit** [hbgit/Map2Check#30]
**Add support for new reach function**
Checking out https://github.com/sosy-lab/sv-benchmarks/commit/28369c96c47a133df344c283f0a36d5b761ec3da

**Comment by rafaelsamenezes** [comment]
This should be simple, just change it in TargetPass.

https://github.com/hbgit/Map2Check/blob/master/modules/backend/pass/TargetPass.hpp#L59

**Comment by hbgit** [comment]
Solved, checkout commit https://github.com/hbgit/Map2Check/commit/569d938edbb033a54600c9522d1b43a3402d4fc6
