### ISSUE TITLE
Improving the code style

### ISSUE THREAD

**Issue by hbgit** [hbgit/Map2Check#6]
- [x] Add code style scripts
- [x] Add documentation to apply code style
- [x] Update build script to validate code style

**Comment by RafaelSa94** [comment]
Since we use Google Style for c/cpp we can also add cpplint into the travis script to validate

**Comment by RafaelSa94** [comment]
Just added the cpplint into the travis in feature/code_style, it found 544 errors

**Comment by RafaelSa94** [comment]
Also, we are applying the clang-format in LLVM [for all the backend files](https://github.com/hbgit/Map2Check/blob/feature/code_style/check_code_style.py#L35). Since backend/pass contains CPP files shoudn't we use the Google CS?

**Comment by hbgit** [comment]
> Just added the cpplint into the travis in feature/code_style, it found 544 errors I verified the flags used in the python script and only applied the travis in the Pass and Frontend, it found 127 errors

I would suggest you apply our check_code_style.py also in the travis file.

**Comment by hbgit** [comment]
> Also, we are applying the clang-format in LLVM [for all the backend files](https://github.com/hbgit/Map2Check/blob/feature/code_style/check_code_style.py#L35). Since backend/pass contains CPP files shoudn't we use the Google CS?

Okay, thanks to note that. I'll fix this in the check_code_style.py script.

**Comment by RafaelSa94** [comment]
Are we going to verify python CS as well?

**Comment by hbgit** [comment]
> Are we going to verify python CS as well?

Not for while, the check_code_style.py script just aims to fix the format (using clang-format) and check (using cpplint for C++) the code style.
